// <auto-generated />
using System;
using ContactApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250527135832_UpdateDatabaseSchema")]
    partial class UpdateDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ContactApp.Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataUrodzenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PodkategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KategoriaId");

                    b.HasIndex("PodkategoriaId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Email = "test@test.pl",
                            HasloHash = "ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae",
                            Imie = "Test",
                            KategoriaId = 2,
                            Nazwisko = "Testowski",
                            Telefon = "111222333"
                        });
                });

            modelBuilder.Entity("ContactApp.Api.Models.ContactCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Służbowy"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Prywatny"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Inny"
                        });
                });

            modelBuilder.Entity("ContactApp.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan@example.com",
                            HasloHash = "a15f8ae07675bfb96e084bfb4f52fb2c22091061aae86e0eb76a55f4e52dd74e",
                            Imie = "Jan"
                        });
                });

            modelBuilder.Entity("ContactSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("ContactSubcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriaId = 1,
                            Nazwa = "Szef"
                        },
                        new
                        {
                            Id = 2,
                            KategoriaId = 1,
                            Nazwa = "Klient"
                        },
                        new
                        {
                            Id = 3,
                            KategoriaId = 1,
                            Nazwa = "Współpracownik"
                        });
                });

            modelBuilder.Entity("ContactApp.Api.Models.Contact", b =>
                {
                    b.HasOne("ContactApp.Api.Models.ContactCategory", "Kategoria")
                        .WithMany()
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactSubcategory", "Podkategoria")
                        .WithMany()
                        .HasForeignKey("PodkategoriaId");

                    b.Navigation("Kategoria");

                    b.Navigation("Podkategoria");
                });

            modelBuilder.Entity("ContactSubcategory", b =>
                {
                    b.HasOne("ContactApp.Api.Models.ContactCategory", "Kategoria")
                        .WithMany()
                        .HasForeignKey("KategoriaId");

                    b.Navigation("Kategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
