// <auto-generated />
using System;
using ContactApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526113713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ContactApp.Api.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataUrodzenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PodkategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KategoriaId");

                    b.HasIndex("PodkategoriaId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataUrodzenia = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jan.kowalski@example.com",
                            HasloHash = "haslo123",
                            Imie = "Jan",
                            KategoriaId = 1,
                            Nazwisko = "Kowalski",
                            PodkategoriaId = 2,
                            Telefon = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            DataUrodzenia = new DateTime(1992, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.nowak@example.com",
                            HasloHash = "haslo456",
                            Imie = "Anna",
                            KategoriaId = 2,
                            Nazwisko = "Nowak",
                            Telefon = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            DataUrodzenia = new DateTime(1975, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "piotr.zielinski@example.com",
                            HasloHash = "haslo789",
                            Imie = "Piotr",
                            KategoriaId = 3,
                            Nazwisko = "Zieliński",
                            Telefon = "555111222"
                        });
                });

            modelBuilder.Entity("ContactApp.Api.Models.ContactCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Służbowy"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Prywatny"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Inny"
                        });
                });

            modelBuilder.Entity("ContactSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactSubcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Szef"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Klient"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Współpracownik"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Dostawca"
                        });
                });

            modelBuilder.Entity("ContactApp.Api.Models.Contact", b =>
                {
                    b.HasOne("ContactApp.Api.Models.ContactCategory", "Kategoria")
                        .WithMany()
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactSubcategory", "Podkategoria")
                        .WithMany()
                        .HasForeignKey("PodkategoriaId");

                    b.Navigation("Kategoria");

                    b.Navigation("Podkategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
